[book]
title = "januborer's site"
authors = ["januborer"]
language = "en"
src = "src"
description = "januborer site"

[build]
build-dir = "book"
create-missing = true
use-default-preprocessors = true


[output.html.print]
enable = false
page-break = true

[output.html.fold]
enable = false
level = 0

# [output.html.playground]
# editable = false         # allows editing the source code
# copyable = true          # include the copy button for copying code snippets
# copy-js = true           # includes the JavaScript for the code editor
# line-numbers = false     # displays line numbers for editable code
# runnable = true          # displays a run button for rust code


[output.html.search]
enable = true            # enables the search feature
limit-results = 30       # maximum number of search results
teaser-word-count = 30   # number of words used for a search result teaser
use-boolean-and = true   # multiple search terms must all match
boost-title = 2          # ranking boost factor for matches in headers
boost-hierarchy = 1      # ranking boost factor for matches in page names
boost-paragraph = 1      # ranking boost factor for matches in text
expand = true            # partial words will match longer terms
heading-split-level = 3  # link results to heading levels
copy-js = true           # include Javascript code for search


[output.html.playground]
editable = true
runnable = false
# editor = "/path/to/editor"
